language: objective-c
xcode_project: ImageCycleScrollView.xcodeproj # path to your xcodeproj folder
xcode_scheme: ImageCycleScrollView
osx_image: xcode8.3
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
