language: objective-c
xcode_project: ImageCycleScrollView.xcodeproj # path to your xcodeproj folder
xcode_scheme: ImageCycleScrollView
osx_image: xcode8.3
-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
